// src/app/purchase-xp/purchase-xp.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common'; // For NgIf, NgClass
import { FormsModule } from '@angular/forms'; // For NgModel
import { Router } from '@angular/router';
import { GenericSuccessModalComponent } from "../generic-success-modal/generic-success-modal.component";
import { NavbarComponentComponent } from "../navbar-component/navbar-component.component";
import { PaymentService } from '../services/payment.service';
import { Payment, User } from '../types';
import { UserService } from '../services/user.service';

@Component({
  selector: 'app-purchase-xp',
  standalone: true, // Mark as standalone
  imports: [CommonModule, FormsModule, GenericSuccessModalComponent, NavbarComponentComponent], // Import necessary modules
  templateUrl: './purchase-xp.component.html',
  styleUrls: ['./purchase-xp.component.css']
})
export class PurchaseXpComponent implements OnInit {

  // Current step of the process (1: XP input, 2: Payment/QR code)
  currentStep: 1 | 2 = 1;

  // XP amount requested by the user
  xpAmount: number | null = null;
  // Total cost calculated based on XP amount
  totalAmount: number = 0;

  // Constants for XP rules
  readonly XP_RATE_PER_RUPEE = 5; // 1 XP = 5 Rs
  readonly MIN_XP = 20;
  readonly MAX_XP = 100;

  // Messages for validation or information
  errorMessage: string | null = null;
  infoMessage: string | null = null;
  successMessage: string | null = null; // New: for API success messages

  // Placeholder for QR code URL (In a real app, this would be dynamically generated by a payment gateway)
  qrCodeUrl: string = 'https://placehold.co/300x300/E5E7EB/6B7280?text=QR+Code+Placeholder';

  showPurchaseSuccessModal: boolean = false;
  isLoading: boolean = false; // New: To indicate API call in progress
  user:User|null=null;
  // Placeholder for user ID - In a real app, this would come from an authentication service
  private currentUserId: number = 123; // Example User ID

  constructor(
    private router: Router,
    private paymentService:PaymentService,
    private userService:UserService
  ) { }

  ngOnInit(): void {
    this.updateInfoMessage(); // Display initial info message
  }

  /**
   * Updates the informational message below the XP input field.
   */
  updateInfoMessage(): void {
    this.infoMessage = `Minimum XP: ${this.MIN_XP}, Maximum XP: ${this.MAX_XP}.`;
  }

  /**
   * Calculates the total amount based on the XP amount entered.
   */
  calculateAmount(): void {
    this.errorMessage = null; // Clear previous errors
    if (this.xpAmount !== null && this.xpAmount >= this.MIN_XP && this.xpAmount <= this.MAX_XP) {
      this.totalAmount = this.xpAmount * this.XP_RATE_PER_RUPEE;
    } else {
      this.totalAmount = 0; // Reset amount if input is invalid
    }
  }

  /**
   * Validates the XP amount and proceeds to the payment step (without API call yet).
   */
  proceedToPay(): void {
    this.errorMessage = null; // Clear previous errors
    this.successMessage = null; // Clear previous success messages

    if (this.xpAmount === null || this.xpAmount < this.MIN_XP || this.xpAmount > this.MAX_XP) {
      this.errorMessage = `Please enter an XP amount between ${this.MIN_XP} and ${this.MAX_XP}.`;
      this.totalAmount = 0; // Reset amount
      return;
    }
    const username=localStorage.getItem('username');
    this.userService.getByUserName(username!).subscribe({
      next:(userData:User)=>{
        this.user=userData;
        console.log("PurchaseModal : fetched the user");
      },
      error:(err)=>{
        console.log("PurchaseModal : unable to fetch the user");
        this.user=null;
      }
    });
    this.calculateAmount(); // Ensure amount is up-to-date
    this.currentStep = 2; // Move to the payment step
    console.log(`Proceeding to pay for ${this.xpAmount} XP, total amount: ₹${this.totalAmount}`);
    // In a real application, you would generate a unique QR code or payment link here.
    // this.qrCodeUrl = 'YOUR_DYNAMIC_QR_CODE_URL_FROM_PAYMENT_GATEWAY_API';
  }

  /**
   * Navigates back to the XP input step.
   */
  goBack(): void {
    this.currentStep = 1;
    this.errorMessage = null; // Clear any messages when going back
    this.successMessage = null; // Clear success messages too
    console.log('Going back to XP input step.');
  }

  /**
   * Makes the API call to confirm payment and purchase XP.
   */
  confirmPayment(): void {
    this.errorMessage = null; // Clear previous errors
    this.successMessage = null; // Clear previous success messages

    if (this.xpAmount === null || this.xpAmount <= 0) {
      this.errorMessage = 'XP amount is invalid for payment confirmation.';
      return;
    }

    this.isLoading = true; // Set loading state
    console.log(`Confirming payment for ${this.xpAmount} XP for user ${this.currentUserId}...`);

    // Call the XP service to buy XP
    this.paymentService.buyXp(this.user?.id!, this.xpAmount).subscribe({
      next: (payment: Payment) => {
        this.isLoading = false; // Clear loading state
        this.successMessage = `XP purchase successful! Payment ID: ${payment.id}, Mode: ${payment.mode}, XP Purchased: ${payment.xpPurchased}`;
        console.log('Payment successful:', payment);
        this.showPurchaseSuccessModal = true; // Show success modal after successful API call
      },
      error: (error) => {
        this.isLoading = false; // Clear loading state
        this.errorMessage = `Error confirming payment: ${error.message || 'An unknown error occurred.'}`;
        console.error('Error confirming payment:', error);
      }
    });
  }

  closePurchaseSuccessModal(): void {
    console.log('Purchase Success Modal closed.');
    this.showPurchaseSuccessModal = false;
    this.resetComponent();
    // Optionally navigate or refresh data here
  }

  handlePrimaryPurchaseAction(): void {
    console.log('Primary action from Purchase Success Modal: Navigating to profile.');
    this.showPurchaseSuccessModal = false; // Close the modal
    this.resetComponent();
    this.router.navigate(['/profile']); // Example navigation
  }

  /**
   * Simulates payment cancellation.
   */
  cancelPayment(): void {
    console.log('Payment cancelled.');
    this.resetComponent(); // Reset for a new transaction
  }

  /**
   * Resets the component to its initial state.
   */
  resetComponent(): void {
    this.currentStep = 1;
    this.xpAmount = null;
    this.totalAmount = 0;
    this.errorMessage = null;
    this.successMessage = null; // Clear success message on reset
    this.updateInfoMessage(); // Reset info message
  }
}
